-- =============================================================================
-- Nyaya-Mitra | Legal Tech RAG Application
-- Database Schema Initialization Script
-- =============================================================================
--
-- PURPOSE:
--   This script sets up the complete PostgreSQL database schema for the
--   Nyaya-Mitra application from scratch. It is idempotent — safe to run
--   multiple times. Each run drops existing tables and recreates them cleanly.
--
-- HOW TO RUN:
--   Option 1 (Supabase SQL Editor): Copy-paste this entire file and execute.
--   Option 2 (psql CLI):
--     psql "postgresql://postgres.[ref]:[password]@db.[ref].supabase.co:5432/postgres" \
--       -f db/schema.sql
--   Option 3 (Node.js init script):
--     node db/scripts/initDb.js   (reads and executes this file)
--
-- ⚠️  WARNING: The DROP TABLE statements below are DESTRUCTIVE.
--   All existing data will be permanently deleted. Only run this against
--   a fresh database or when intentionally resetting a development environment.
--   For production migrations, use a migration tool like node-pg-migrate or Flyway.
--
-- TABLE EXECUTION ORDER (respects Foreign Key dependencies):
--   1. Extensions
--   2. users                  (no dependencies)
--   3. user_documents         (depends on: users)
--   4. document_clauses       (depends on: user_documents)
--   5. chat_history           (depends on: users)
--   6. legal_knowledge_base   (no FK dependencies; requires pgvector)
--
-- =============================================================================
-- =============================================================================
-- STEP 1: Enable Required PostgreSQL Extensions
-- =============================================================================
-- pgvector: Adds vector data types (vector, halfvec, sparsevec) and similarity
-- search operators (<->, <=>, <#>) to PostgreSQL. This is pre-installed on
-- Supabase and must be enabled per-database via CREATE EXTENSION.
--
-- halfvec: A 16-bit float ("half precision") variant of the vector type.
-- We use halfvec(3072) instead of vector(3072) to store Gemini's
-- text-embedding-001 output because:
--   - PostgreSQL has an 8KB page size limit.
--   - vector(3072) = 3072 × 4 bytes = ~12KB → EXCEEDS the limit.
--   - halfvec(3072) = 3072 × 2 bytes = ~6KB → FITS within the limit.
-- Using halfvec makes full-vector HNSW indexing possible without
-- quantization tricks.
CREATE EXTENSION IF NOT EXISTS vector;
-- =============================================================================
-- STEP 2: Drop Existing Tables (Clean Slate)
-- =============================================================================
-- Drop in REVERSE dependency order (children before parents) to avoid
-- Foreign Key constraint violations.
DROP TABLE IF EXISTS legal_knowledge_base CASCADE;
DROP TABLE IF EXISTS chat_history CASCADE;
DROP TABLE IF EXISTS document_clauses CASCADE;
DROP TABLE IF EXISTS user_documents CASCADE;
DROP TABLE IF EXISTS users CASCADE;
-- =============================================================================
-- STEP 3: Create Tables
-- =============================================================================
-- -----------------------------------------------------------------------------
-- Table: users
-- Stores registered users of the Nyaya-Mitra application.
-- -----------------------------------------------------------------------------
CREATE TABLE users (
  -- Primary Key: UUID generated by the database. Using gen_random_uuid()
  -- (available natively in PostgreSQL 13+) produces cryptographically random
  -- UUIDs, which are safe to expose in API responses (unlike sequential integers).
  user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Full legal name of the user. Required for personalization.
  name VARCHAR(255) NOT NULL,
  -- Email address used for authentication. Must be globally unique.
  email VARCHAR(255) NOT NULL UNIQUE,
  -- The user's preferred language for AI responses (e.g., 'hindi', 'english',
  -- 'tamil'). Defaults to English. This is passed as a hint to the Gemini LLM.
  preferred_language VARCHAR(50) NOT NULL DEFAULT 'english',
  -- Audit timestamp. timezone='utc' ensures consistency regardless of
  -- the server's local timezone setting.
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
COMMENT ON TABLE users IS 'Registered users of the Nyaya-Mitra application.';
COMMENT ON COLUMN users.user_id IS 'Surrogate primary key; UUID avoids enumeration attacks.';
COMMENT ON COLUMN users.preferred_language IS 'BCP-47 language tag or simple name; used to localize AI responses.';
-- -----------------------------------------------------------------------------
-- Table: user_documents
-- Stores legal documents uploaded by users for analysis (e.g., contracts,
-- FIRs, rent agreements). The raw text is extracted server-side and stored
-- alongside the AI-generated analysis.
-- -----------------------------------------------------------------------------
CREATE TABLE user_documents (
  doc_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- FK to users. ON DELETE CASCADE: if a user account is deleted, all their
  -- documents are automatically deleted too (GDPR / data hygiene).
  user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  -- Original filename as uploaded by the user (e.g., "rent_agreement_2024.pdf").
  document_name VARCHAR(500) NOT NULL,
  -- Full extracted text content of the uploaded document.
  -- TEXT in PostgreSQL is unlimited in length, suitable for large legal docs.
  raw_text TEXT NOT NULL,
  -- Risk assessment level assigned by the Gemini LLM after analysis.
  -- Constrained to a defined set of values for reliable filtering/display.
  risk_level VARCHAR(20) CHECK (
    risk_level IN ('low', 'medium', 'high', 'critical')
  ),
  -- The AI-generated plain-language summary of the document, optionally
  -- in the user's preferred_language.
  generated_summary TEXT,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
COMMENT ON TABLE user_documents IS 'Legal documents uploaded by users for AI analysis.';
COMMENT ON COLUMN user_documents.raw_text IS 'Server-side extracted text from PDF/DOCX.';
COMMENT ON COLUMN user_documents.risk_level IS 'Risk category assigned by the LLM; NULL means not yet analyzed.';
COMMENT ON COLUMN user_documents.generated_summary IS 'Plain-language summary of the document in the user''s preferred language.';
-- -----------------------------------------------------------------------------
-- Table: document_clauses
-- Stores individual clause analyses from uploaded documents.
-- Each clause extracted from a document is analyzed for legal risks and
-- its analysis results are stored here for later retrieval.
-- -----------------------------------------------------------------------------
CREATE TABLE document_clauses (
  clause_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- FK to user_documents. ON DELETE CASCADE: if a document is deleted,
  -- all its clause analyses are automatically deleted too.
  doc_id UUID NOT NULL REFERENCES user_documents(doc_id) ON DELETE CASCADE,
  -- Sequential clause number within the document (1, 2, 3, ...)
  clause_number INTEGER NOT NULL,
  -- The actual text of this clause as extracted from the document
  clause_text TEXT NOT NULL,
  -- Whether this clause was flagged as risky by the LLM
  is_risky BOOLEAN NOT NULL DEFAULT false,
  -- Risk severity level: 'low', 'medium', 'high', 'critical', or NULL if not risky
  risk_level VARCHAR(20) CHECK (
    risk_level IN ('low', 'medium', 'high', 'critical')
  ),
  -- One-sentence description of the legal issue (NULL if not risky)
  issue TEXT,
  -- The specific article/section of law that applies (NULL if not risky)
  relevant_law TEXT,
  -- Recommended action to address this clause (NULL if not risky)
  recommendation TEXT,
  -- CSV of relevant law texts retrieved during analysis (for transparency)
  retrieved_laws TEXT,
  -- Timestamp when this analysis was created
  analyzed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
COMMENT ON TABLE document_clauses IS 'Individual clause analyses for uploaded documents.';
COMMENT ON COLUMN document_clauses.doc_id IS 'Foreign key to user_documents; cascades on delete.';
COMMENT ON COLUMN document_clauses.is_risky IS 'Boolean flag indicating if LLM identified legal risks.';
COMMENT ON COLUMN document_clauses.risk_level IS 'Risk severity; NULL if is_risky is false.';
-- Index for fast retrieval of all clauses in a document
CREATE INDEX idx_document_clauses_doc_id ON document_clauses (doc_id);
-- Index for filtering risky clauses
CREATE INDEX idx_document_clauses_is_risky ON document_clauses (doc_id, is_risky);
-- -----------------------------------------------------------------------------
-- Table: chat_history
-- Stores the conversation log between users and the Nyaya-Mitra AI assistant.
-- Used to retrieve the last N messages for conversation context injection
-- into the Gemini LLM prompt (sliding window memory).
-- -----------------------------------------------------------------------------
CREATE TABLE chat_history (
  message_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- FK to users. ON DELETE CASCADE: deleting a user purges their chat history.
  user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  -- The user's original question or message, stored verbatim.
  query_text TEXT NOT NULL,
  -- The AI assistant's response to the query.
  ai_response TEXT NOT NULL,
  -- When this exchange happened. Used for ordering (ORDER BY timestamp DESC)
  -- to retrieve the most recent N messages for context.
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
COMMENT ON TABLE chat_history IS 'Full conversation log for each user session with the AI assistant.';
COMMENT ON COLUMN chat_history.query_text IS 'Verbatim user query as submitted.';
COMMENT ON COLUMN chat_history.ai_response IS 'The full AI-generated response, potentially in the user''s preferred language.';
-- Index on (user_id, timestamp DESC) to make the "get last N messages for user"
-- query (ORDER BY timestamp DESC LIMIT N) extremely fast via index-only scan.
CREATE INDEX idx_chat_history_user_timestamp ON chat_history (user_id, timestamp DESC);
-- -----------------------------------------------------------------------------
-- Table: legal_knowledge_base
-- The RAG knowledge corpus. Stores pre-chunked legal text (IPC sections,
-- CrPC articles, High Court judgements, legal guides, etc.) alongside their
-- Gemini-generated semantic embedding vectors.
--
-- How it's used in the RAG pipeline:
--   1. User asks a question → Gemini embeds it → 3072-dim halfvec query.
--   2. App runs ANN (Approximate Nearest Neighbor) search via HNSW index.
--   3. Top-K most semantically similar chunks are retrieved.
--   4. Those chunks become the "context" injected into the Gemini LLM prompt.
--   5. Gemini generates a grounded, source-cited answer.
-- -----------------------------------------------------------------------------
CREATE TABLE legal_knowledge_base (
  -- SERIAL: Auto-incrementing integer PK. UUIDs are unnecessary here since this
  -- table is only accessed internally by the RAG pipeline (never exposed in URLs).
  -- SERIAL integers are also faster to join and index than UUIDs.
  vector_id SERIAL PRIMARY KEY,
  -- The data source this chunk originated from.
  -- Examples: 'IPC_1860', 'CrPC_1973', 'SupremeCourt_Judgements', 'Legal_Aid_Guide'
  dataset_source VARCHAR(255) NOT NULL,
  -- The type of legal document.
  -- Examples: 'statute', 'judgement', 'faq', 'explainer', 'form'
  -- Used as a metadata filter in semantic search (e.g., "only search statutes").
  document_type VARCHAR(100) NOT NULL,
  -- The actual text content of this chunk. This is what gets injected into
  -- the LLM prompt as retrieved context. Chunk size should be tuned to balance
  -- semantic coherence with LLM context window limits (typically 256-512 tokens).
  content_text TEXT NOT NULL,
  -- The semantic embedding vector for content_text, generated by
  -- Google's gemini-embedding-001 model (dimensions: 3072).
  --
  -- DATA TYPE RATIONALE — halfvec vs vector:
  --   PostgreSQL stores table rows in 8KB pages. A standard vector(3072)
  --   occupies 3072 × 4 bytes = 12,288 bytes — larger than one page.
  --   halfvec(3072) uses 16-bit floats: 3072 × 2 bytes = 6,144 bytes,
  --   which fits comfortably. The ~0.1% accuracy loss from float32→float16
  --   quantization is negligible for semantic search use cases.
  embedding HALFVEC(3072)
);
COMMENT ON TABLE legal_knowledge_base IS 'RAG knowledge corpus: pre-chunked legal text with semantic embeddings.';
COMMENT ON COLUMN legal_knowledge_base.embedding IS 'halfvec(3072): Gemini gemini-embedding-001 vector quantized to float16 to fit PostgreSQL 8KB page limit.';
COMMENT ON COLUMN legal_knowledge_base.document_type IS 'Metadata for filtered semantic search (e.g., only search statutes or judgements).';
-- =============================================================================
-- STEP 4: Create the HNSW Vector Index on legal_knowledge_base
-- =============================================================================
--
-- WHY HNSW (Hierarchical Navigable Small World)?
--   A brute-force cosine similarity scan over millions of vectors is O(N).
--   HNSW is an Approximate Nearest Neighbor (ANN) algorithm that builds a
--   multi-layer graph structure enabling sub-linear O(log N) search with
--   very high recall (typically >95%).
--
-- INDEX PARAMETERS:
--   m          = 16  — Number of bi-directional links per node. Higher = better
--                       recall + more memory. Default is 16.
--   ef_construction = 64 — Search width during index construction. Higher = better
--                       index quality + slower build time. Default is 64.
--
-- OPERATOR CLASS:
--   halfvec_cosine_ops — Optimizes for COSINE DISTANCE (<=>).
--   Cosine similarity is the correct metric for comparing Gemini embeddings,
--   as they are unit-normalized in the embedding space. It measures the ANGLE
--   between vectors (semantic direction) rather than their magnitude.
--
-- SEARCH PARAMETER (runtime, not index-level):
--   SET hnsw.ef_search = 100; — Controls search-time recall vs. latency trade-off.
--   Higher = more candidates explored = better recall, slower query.
--   Set this per-session or per-query for the semantic search queries.
--
CREATE INDEX idx_legal_kb_embedding_hnsw ON legal_knowledge_base USING hnsw (embedding halfvec_cosine_ops) WITH (m = 16, ef_construction = 64);
-- Standard B-tree index for fast metadata filtering (e.g., WHERE document_type = 'statute').
-- Useful when the application does filtered vector searches.
CREATE INDEX idx_legal_kb_document_type ON legal_knowledge_base (document_type);
CREATE INDEX idx_legal_kb_dataset_source ON legal_knowledge_base (dataset_source);
-- =============================================================================
-- STEP 5: Verification Query (optional, for manual runs)
-- =============================================================================
-- After running this script, execute the following to confirm all objects
-- were created successfully:
--
-- SELECT table_name FROM information_schema.tables
--   WHERE table_schema = 'public'
--   ORDER BY table_name;
--
-- SELECT indexname, indexdef FROM pg_indexes
--   WHERE tablename = 'legal_knowledge_base';
-- =============================================================================