# Generated by Django 4.2.30 on 2026-04-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the document text', max_length=64, unique=True)),
                ('bias_score', models.IntegerField()),
                ('summary_text', models.TextField()),
                ('red_flags', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='ID of the user who uploaded the document', max_length=255)),
                ('file_url', models.URLField(help_text='URL where the document file is stored', max_length=1000)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
