# Generated by Django 4.2.30 on 2026-04-19 20:39

from django.db import migrations, models
import pgvector.django.vector
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('document_analysis', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeBaseLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_act', models.CharField(default='Model Tenancy Act 2021', help_text='Source of the law', max_length=255)),
                ('clause_text', models.TextField(help_text='The actual text of the law clause')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, help_text='Gemini text-embedding-004 representation')),
            ],
        ),
    ]
