# Generated by Django 4.2.30 on 2026-04-19 20:50

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('document_analysis', '0002_knowledgebaselaw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebaselaw',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=3072, help_text='Gemini text-embedding-004 representation'),
        ),
    ]
